parameters:
  

jobs:
  - job:
    pool:
      name: ${{ parameters.agentPool }}
      vmImage: ${{ parameters.vmImage }}

 # if this is just a feature branch then we don't want to do any publishing
    steps:
    - ${{ if in(variables['Build.SourceBranchName'], 'main') }}:
      - task: Docker@2
        displayName: Login to ACR
        inputs:
          command: login
          containerRegistry: ${{ parameters.acrDockerReg}}

      - task: Docker@2
        displayName: '${{ parameters.buildContainerDisplayName }} - v$(Build.BuildId)'
        inputs:
          repository: ${{ parameters.imageName }}
          command: build
          Dockerfile: Dockerfile
          containerRegistry: ${{ parameters.acrDockerReg }}
          arguments: --build-arg NPM_TOKEN=$(NPM_TOKEN)
          tags: |
            v$(Build.BuildId)
            latest

      #Push container image with build version tag
      - task: Docker@2
        displayName: 'Push container image'
        inputs:
          repository: ${{ parameters.imageName }}
          containerRegistry: ${{ parameters.acrDockerReg }}
          command: push
          tags: |
            v$(Build.BuildId)
            latest
